apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trendify
  template:
    metadata:
      labels:
        app: trendify
    spec:
      containers:
      - name: trendify
        image: dprakash4a3/trendify-app
        ports:
        - containerPort: 80
