apiVersion: v1
kind: Service
metadata:
  name: trendify-service
spec:
  type: LoadBalancer
  selector:
    app: trendify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
